name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Login to Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
      #run: docker build . --file Dockerfile --tag zerosum:$(date +%s)
    - name: Docker Build and Push
      uses: docker/build-push-action@v2.7.0
      with:
        context: ../../
        file: ./Dockerfile
        push: true
        tags: |
          raulc27/zerosum:latest
          raulc27/zerosum:${{ github.run_number }}
